//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegEditor {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    public sealed partial class Theme : global::System.Configuration.ApplicationSettingsBase {
        
        private static Theme defaultInstance = ((Theme)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Theme())));
        
        public static Theme Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("246, 246, 246")]
        public global::System.Drawing.Color DefaultButtonBackColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultButtonBackColor"]));
            }
            set {
                this["DefaultButtonBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color DefaultButtonForeColor {
            get {
                return ((global::System.Drawing.Color)(this["DefaultButtonForeColor"]));
            }
            set {
                this["DefaultButtonForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("246, 246, 246")]
        public global::System.Drawing.Color FormBackColor {
            get {
                return ((global::System.Drawing.Color)(this["FormBackColor"]));
            }
            set {
                this["FormBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("246, 246, 246")]
        public global::System.Drawing.Color DataGridViewBackColor {
            get {
                return ((global::System.Drawing.Color)(this["DataGridViewBackColor"]));
            }
            set {
                this["DataGridViewBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("229, 229, 229")]
        public global::System.Drawing.Color DataGridViewRowsBackColor {
            get {
                return ((global::System.Drawing.Color)(this["DataGridViewRowsBackColor"]));
            }
            set {
                this["DataGridViewRowsBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color DataGridViewRowsForeColor {
            get {
                return ((global::System.Drawing.Color)(this["DataGridViewRowsForeColor"]));
            }
            set {
                this["DataGridViewRowsForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("246, 246, 246")]
        public global::System.Drawing.Color datagrview_rgb_grid {
            get {
                return ((global::System.Drawing.Color)(this["datagrview_rgb_grid"]));
            }
            set {
                this["datagrview_rgb_grid"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("246, 246, 246")]
        public global::System.Drawing.Color combox_rgb_bg {
            get {
                return ((global::System.Drawing.Color)(this["combox_rgb_bg"]));
            }
            set {
                this["combox_rgb_bg"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::MetroFramework.MetroColorStyle TextBoxStyle {
            get {
                return ((global::MetroFramework.MetroColorStyle)(this["TextBoxStyle"]));
            }
            set {
                this["TextBoxStyle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::MetroFramework.MetroColorStyle chkbox_style {
            get {
                return ((global::MetroFramework.MetroColorStyle)(this["chkbox_style"]));
            }
            set {
                this["chkbox_style"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("246, 246, 246")]
        public global::System.Drawing.Color TextBoxBackColor {
            get {
                return ((global::System.Drawing.Color)(this["TextBoxBackColor"]));
            }
            set {
                this["TextBoxBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TextBoxForeColor {
            get {
                return ((global::System.Drawing.Color)(this["TextBoxForeColor"]));
            }
            set {
                this["TextBoxForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DodgerBlue")]
        public global::System.Drawing.Color ComboboxForeColor {
            get {
                return ((global::System.Drawing.Color)(this["ComboboxForeColor"]));
            }
            set {
                this["ComboboxForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("246, 246, 246")]
        public global::System.Drawing.Color MenuStripBackColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripBackColor"]));
            }
            set {
                this["MenuStripBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color MenuStripForeColor {
            get {
                return ((global::System.Drawing.Color)(this["MenuStripForeColor"]));
            }
            set {
                this["MenuStripForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("246, 246, 246")]
        public global::System.Drawing.Color RootsTreeViewBackColor {
            get {
                return ((global::System.Drawing.Color)(this["RootsTreeViewBackColor"]));
            }
            set {
                this["RootsTreeViewBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color RootsTreeViewForeColor {
            get {
                return ((global::System.Drawing.Color)(this["RootsTreeViewForeColor"]));
            }
            set {
                this["RootsTreeViewForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color CancelButtonBackColor {
            get {
                return ((global::System.Drawing.Color)(this["CancelButtonBackColor"]));
            }
            set {
                this["CancelButtonBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color CancelButtonForeColor {
            get {
                return ((global::System.Drawing.Color)(this["CancelButtonForeColor"]));
            }
            set {
                this["CancelButtonForeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::MetroFramework.MetroColorStyle combox_style {
            get {
                return ((global::MetroFramework.MetroColorStyle)(this["combox_style"]));
            }
            set {
                this["combox_style"] = value;
            }
        }
    }
}
